# Generated by Django 5.0.1 on 2026-07-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='media', max_length=10)),
                ('concluida', models.BooleanField(default=False)),
                ('data', models.DateField()),
                ('criada_em', models.TimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-prioridade', 'concluida', 'criada_em'],
            },
        ),
    ]
